# Generated by Django 5.2.6 on 2025-10-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_spotify_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('watched', 'Watched Movie'), ('rated', 'Rated Movie'), ('reviewed', 'Reviewed Movie'), ('loved', 'Loved Movie'), ('liked', 'Liked Movie'), ('listened', 'Listened to Song')], max_length=20)),
                ('movie_id', models.CharField(blank=True, max_length=20, null=True)),
                ('movie_title', models.CharField(blank=True, max_length=255)),
                ('movie_poster', models.URLField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True)),
                ('song_id', models.CharField(blank=True, max_length=100, null=True)),
                ('song_name', models.CharField(blank=True, max_length=255)),
                ('song_artist', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
