# Render Blueprint for Tunr (Monorepo: backend + frontend)
services:
  # Django Backend API
  - type: web
    name: tunr-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate --no-input"
    startCommand: "gunicorn tunr_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tunr-db
          property: connectionString
      - key: OMDB_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
    healthCheckPath: /

  # React Frontend (Static Site)
  - type: web
    name: tunr-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_OMDB_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: tunr-db
    plan: free
    databaseName: tunr
    user: tunr_user
