# Generated by Django 5.2.6 on 2025-10-30 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('actors', models.TextField(blank=True)),
                ('plot', models.TextField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10)),
                ('runtime', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('preference_score', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-preference_score'],
                'unique_together': {('user', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='UserMovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('favorite', 'Favorite'), ('watchlist', 'Watchlist')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'movie', 'interaction_type')},
            },
        ),
    ]
