# Generated by Django 5.2.6 on 2025-10-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovieinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('watched', 'Watched'), ('want_to_watch', 'Want to Watch'), ('like', 'Like'), ('love', 'Love')], max_length=20),
        ),
    ]
