# Generated by Django 5.2.6 on 2025-11-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedsong',
            name='album_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='playlist_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
